### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [3]:
import numpy as np
# 1
lista = []
for i in range(10):
    lista.append(i)
print(lista)

lista = [i for i in range(10)]
print(lista)

# 2
lista = []
for i in "parola":
    lista.append(i)
print(lista)

lista = [i for i in "parola"]
print(lista)

# 3
lista = []
for i in range(20):
    if(i%3 == 0 and i>3):
        lista.append(i)
print(lista)

lista = [i for i in range(20) if i%3 == 0 and i>3]
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['p', 'a', 'r', 'o', 'l', 'a']
['p', 'a', 'r', 'o', 'l', 'a']
[6, 9, 12, 15, 18]
[6, 9, 12, 15, 18]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [17]:
#1
numeri = np.arange(1,10,1)
print(numeri)
#2
print(len(numeri))
print(numeri.size)
#3 se non ricordo male avendo usato degli int in np.arange() dovrebbero essere int e se faccio
numeri2 = np.arange(1.0,10.0,1.0)
print(numeri2)
print(numeri.dtype)
print(numeri2.dtype)
# 4
numeri3 = [i for i in range(1,50) if((all(i%j != 0 for j in range(2,i)) or i == 2) and i > 1)]
print(numeri3)

[1 2 3 4 5 6 7 8 9]
9
9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
int32
float64
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [16]:
a = np.arange(1,10)
print(a)
b = a[3:6]
print(b)
# non so se va bene creare l'array inverso così ma non è specificato come
c = np.arange(9,0,-1)
print(c)
# okay ho visto che esiste .flip 
print(a/c)

al = []
for i in range(1,10):
    al.append(i)
print(al)
bl = al[3:6]
print(bl)
cl = al[::-1]
print(cl)
risultato = []
for i in range(len(al)):
    risultato.append(al[i]/cl[i])
print(risultato)

[1 2 3 4 5 6 7 8 9]
[4 5 6]
[9 8 7 6 5 4 3 2 1]
[0.11111111 0.25       0.42857143 0.66666667 1.         1.5
 2.33333333 4.         9.        ]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[0.1111111111111111, 0.25, 0.42857142857142855, 0.6666666666666666, 1.0, 1.5, 2.3333333333333335, 4.0, 9.0]
