### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [9]:
# 1
import numpy as np
numeri = [i for i in range(2,20) if(all(i%j != 0 for j in range(2,i)))]
numeri = np.array(numeri)

# 2
print(numeri>10)
print(numeri[numeri>10])

# 3
print(numeri%2 == 0)
print(numeri[numeri%2 == 0])

[False False False False  True  True  True  True]
[11 13 17 19]
[ True False False False False False False False]
[2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [22]:
a = np.arange(100).reshape(10,10)
print(a)

print("\n")

b = a[1:4:2,]
print(b)

print("\n")

c = a[2,]
print(c)

print("\n")

print(a/c)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


[[10 11 12 13 14 15 16 17 18 19]
 [30 31 32 33 34 35 36 37 38 39]]


[20 21 22 23 24 25 26 27 28 29]


[[0.         0.04761905 0.09090909 0.13043478 0.16666667 0.2
  0.23076923 0.25925926 0.28571429 0.31034483]
 [0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6
  0.61538462 0.62962963 0.64285714 0.65517241]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [1.5        1.47619048 1.45454545 1.43478261 1.41666667 1.4
  1.38461538 1.37037037 1.35714286 1.34482759]
 [2.         1.95238095 1.90909091 1.86956522 1.83333333 1.8
  1.76923077 1.74074074 1.71428571 1.68965517]
 [2.5        2.42857143 2

### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [ ]:
a = np.random.rand(10,3)
print(a)

colonna = np.abs(a-0.5).argmin(axis=1)
riga = np.arange(10)

a[riga,colonna]

[[0.7421828  0.50253468 0.53216841]
 [0.19163678 0.4442755  0.60192612]
 [0.66233783 0.55344458 0.94755023]
 [0.2866425  0.5550251  0.08393354]
 [0.95831679 0.34460992 0.02834502]
 [0.16339823 0.01641858 0.96943838]
 [0.34973266 0.22134225 0.4378988 ]
 [0.11028257 0.06144167 0.76715358]
 [0.62150227 0.09345214 0.64366661]
 [0.21070848 0.55939889 0.92193425]]


array([0.50253468, 0.4442755 , 0.55344458, 0.5550251 , 0.34460992,
       0.16339823, 0.4378988 , 0.76715358, 0.62150227, 0.55939889])

### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [ ]:
# 1
freq = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
print(freq)

# 2
print(np.min(freq))

# 3
print(np.max(freq))

# 4
print((len(freq[freq>120])/len(freq))*100)

# 4 ma con le righieste (funzione di sintesi?)
a = freq>120
print(a)
np.mean(a)*100 # conta mean come funzione di sintesi?

[ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70]
60
164
52.38095238095239
[False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]


52.38095238095239

### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [ ]:
#1
a = np.array([50000,105250,55000,89000])
print("--1--")
print(a)
costoprima = np.sum(a)
print(costoprima)
print(a.dtype)
# 2
print("--2--")
a = np.where(a == 105250, a*1.15,a)
print(a.dtype)
print(a)
#3 sinceramente non sto capendo, si è presente, probabilmente moltiplicando per 1.15 ha cambiato il tipo dell'array
# 4
print("--4--")
b = np.array([50000,105250,55000,89000], dtype = np.float64)
b = np.where(b == 105250, b*1.15,b)
print(b)
#5
print("--5--")
a = np.where(a == 50000, a*1.2,a)
print(a)
# 6
print("--6--")
originale = np.array([50000,105250,55000,89000])
a = np.where(a == originale, a*1.1,a)
print(a)
#7
print("--7--")
costodopo = np.sum(a)
print(costodopo)
print(costodopo - costoprima) # un po'

--1--
[ 50000 105250  55000  89000]
299250
int32
--2--
float64
[ 50000.  121037.5  55000.   89000. ]
--4--
[ 50000.  121037.5  55000.   89000. ]
--5--
[ 60000.  121037.5  55000.   89000. ]
--6--
[ 60000.  121037.5  60500.   97900. ]
--7--
339437.5
40187.5


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [7]:
# 1
print("--1--")
import numpy as np
emissioni = np.loadtxt("../data/emissioni.txt")
print(emissioni)

# 2
print("--2--")
print("Quante emissioni sono maggiori di 18 tonnellate:", len(emissioni[emissioni>18.00]))
print("Media delle emissioni sopra le 18 tonnellate: ", np.mean(emissioni[emissioni>18.00]))

#3
print("--3--")
print(np.sum(emissioni[emissioni>18.00])/np.sum(emissioni))


--1--
[ 7.01  4.86  4.27 14.39 13.03 13.27 18.43  5.63 17.54 11.75 18.1   7.88
 11.44  7.39 15.75  6.66 10.5   5.13 16.39  6.2  13.13 18.72 18.16 18.03
 17.37 15.9  14.21 12.16 14.13 12.56 15.94 12.91 18.21  8.22 12.   13.55
  9.94 19.82 14.75 19.41 11.7   6.76 18.72  9.66  5.42  6.64 18.27 17.38
 14.45 15.36 15.41 11.23 16.62  7.54 17.37  8.71 13.59  8.63 15.14  6.08
 16.05 16.45 11.62 12.34  8.12 13.86 18.48 11.07  8.72  6.08 17.87  8.32
  4.02 18.07 17.63 18.04 15.42 18.33 16.58 16.23 16.4  17.8  10.91 18.26
  9.93 10.45 10.43  8.19 19.95 15.42 16.02  9.03  4.25 11.14 14.21 14.16
  4.12 14.82 18.22  9.72 10.91  6.43  9.43 11.36 15.9   5.63 18.7   6.31
 19.44  9.46  9.16 12.99 15.72 14.76  4.8  19.49 10.5  16.38  8.59  5.11
 15.58 17.69 17.69 17.4  10.71 17.54 14.18 15.1   8.22 17.07 11.21 11.34
  7.87 18.52  7.23  4.02 17.3  13.65  4.93 17.82 19.46 19.01 14.39 10.59
 10.64  5.31 13.37  5.66  8.86 16.94 13.07 12.54 19.3  17.83  7.57 13.33
 12.6   8.24 16.27 10.99  8.77 11.34 16.38 18

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [24]:
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])
# 1
print("--1--")
print(survey_matrix[survey_matrix[:,2]>12,:])

# 2
print("--2--")
print(survey_matrix[survey_matrix[:,2]>12,1])

# 2
print("--3--")
print(np.mean(survey_matrix[survey_matrix[:,2]>12,:]))

--1--
[[   40 63000    14]
 [   35 58000    13]]
--2--
[63000 58000]
--3--
20183.666666666668


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [32]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])
ages = np.where(ages == 999, np.nan, ages)
print(ages)

np.max(ages) #non capisco perché non vada sinceramente
# allora magari dovevo creare un nuovo array, io ho interpretato così la richiesta
# Sostituire i dati errati con un nan mi sembra la soluzione migliore

np.nanmax(ages)

[ 92. 108.  75.  63.  62.  66.  90.  98.  97.  92.  60. 107.  90.  71.
  97.  86.  55.  55.  98.  57.  96. 104.  96.  94.  72.  98. 111.  98.
  89.  69.  77.  92.  85. 101.  93. 100.  90. 101.  96.  98.  nan  87.
 106.  86. 108.  55.  67.  65.  68.  59.  67.  72.  57.  79.  95.  67.
  86.  70.  91. 111.  67.  75.  59.  88.  90.  99.  94.  65. 111. 103.
 100.  70.  63.  65. 100. 110.  nan  70.  57.  75.  56. 104. 111.  90.
  74. 100.  90.  86.  88.  99.  58. 103.  88. 103.  64.  96. 105.  89.
  83.  65. 100.  62.  73. 105.  83. 105.  58.  96.  77.  74.  95. 109.
  91. 101.  91.  nan  63. 111.  97. 108.  75.  77.  73.  58.  94.  83.
  90.  61. 110. 107. 105.  85.  64.  66.  71. 107. 105.  72.  78.  66.
 100. 102.  72.  nan  74.  68.  73.  72.  90.  93.  99.  55.  92.  83.
  58.  71.  89.  75.  98.  87.  nan  78.  97.  71. 106.  83.  58.  81.
 100.  72.  93.  70.  65.  60.  95. 107.  94.  77.  87.  90.  82.  56.
  99. 107.  86.  56.  73.  96.  64.  69.  64.  92.  57. 104. 110.  69.
  66. 

112.0

### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [28]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]



Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."